name: trackasia_gl_platform_interface
description: A common platform interface for the trackasia_gl plugin.
version: 1.0.2
homepage: https://github.com/track-asia/trackasia-flutter-gl

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5
  typed_data: ^1.3.0

environment:
  sdk: '>=2.16.2 <3.0.0'
  flutter: '>=2.10.0'
